### ISSUE TITLE
lisbn.rb:137:in `parse': undefined method `convert_tags?' for Nori:Class

### ISSUE THREAD

**Issue by jfirebaugh** [ragalie/lisbn#1]
When used with nori 2.0.3, lisbn produces the following error:

```
/Users/john/Development/collect/lisbn/lib/lisbn/lisbn.rb:137:in `parse': undefined method `convert_tags?' for Nori:Class (NoMethodError)
    from /Users/john/Development/collect/lisbn/lib/lisbn/lisbn.rb:120:in `ranges'
    from /Users/john/Development/collect/lisbn/lib/lisbn/lisbn.rb:144:in `<class:Lisbn>'
    from /Users/john/Development/collect/lisbn/lib/lisbn/lisbn.rb:1:in `<top (required)>'
```

Two options:
- specify nori ~> 1.1.4 in the gemspec, or
- figure out the issue and update lisbn to work with 2.0.3
